!function(e){var r={};function t(o){if(r[o])return r[o].exports;var n=r[o]={i:o,l:!1,exports:{}};return e[o].call(n.exports,n,n.exports,t),n.l=!0,n.exports}t.m=e,t.c=r,t.d=function(e,r,o){t.o(e,r)||Object.defineProperty(e,r,{enumerable:!0,get:o})},t.r=function(e){"undefined"!=typeof Symbol&&Symbol.toStringTag&&Object.defineProperty(e,Symbol.toStringTag,{value:"Module"}),Object.defineProperty(e,"__esModule",{value:!0})},t.t=function(e,r){if(1&r&&(e=t(e)),8&r)return e;if(4&r&&"object"==typeof e&&e&&e.__esModule)return e;var o=Object.create(null);if(t.r(o),Object.defineProperty(o,"default",{enumerable:!0,value:e}),2&r&&"string"!=typeof e)for(var n in e)t.d(o,n,function(r){return e[r]}.bind(null,n));return o},t.n=function(e){var r=e&&e.__esModule?function(){return e.default}:function(){return e};return t.d(r,"a",r),r},t.o=function(e,r){return Object.prototype.hasOwnProperty.call(e,r)},t.p="",t(t.s="./src/js/main.js")}({"./src/js/catalog.js":
/*!***************************!*\
  !*** ./src/js/catalog.js ***!
  \***************************/
/*! exports provided: default */function(module,__webpack_exports__,__webpack_require__){"use strict";eval("__webpack_require__.r(__webpack_exports__);\nvar catalogArrow = function catalogArrow() {\n  var arrow = document.querySelector('.footer__content-arrow');\n  var catalog = document.querySelector('.footer__list-catalog');\n  console.log(arrow);\n  arrow.addEventListener('click', function () {\n    arrow.classList.toggle('arrow-active');\n    catalog.classList.toggle('footer__list-active');\n  });\n};\n\n/* harmony default export */ __webpack_exports__[\"default\"] = (catalogArrow);\n\n//# sourceURL=webpack:///./src/js/catalog.js?")},"./src/js/main.js":
/*!************************!*\
  !*** ./src/js/main.js ***!
  \************************/
/*! no exports provided */function(module,__webpack_exports__,__webpack_require__){"use strict";eval('__webpack_require__.r(__webpack_exports__);\n/* harmony import */ var _catalog__WEBPACK_IMPORTED_MODULE_0__ = __webpack_require__(/*! ./catalog */ "./src/js/catalog.js");\n\nwindow.addEventListener(\'DOMContentLoaded\', function () {\n  Object(_catalog__WEBPACK_IMPORTED_MODULE_0__["default"])();\n});\n\n//# sourceURL=webpack:///./src/js/main.js?')}});
//# sourceMappingURL=main.js.map
