!function(t){var e={};function n(o){if(e[o])return e[o].exports;var c=e[o]={i:o,l:!1,exports:{}};return t[o].call(c.exports,c,c.exports,n),c.l=!0,c.exports}n.m=t,n.c=e,n.d=function(t,e,o){n.o(t,e)||Object.defineProperty(t,e,{enumerable:!0,get:o})},n.r=function(t){"undefined"!=typeof Symbol&&Symbol.toStringTag&&Object.defineProperty(t,Symbol.toStringTag,{value:"Module"}),Object.defineProperty(t,"__esModule",{value:!0})},n.t=function(t,e){if(1&e&&(t=n(t)),8&e)return t;if(4&e&&"object"==typeof t&&t&&t.__esModule)return t;var o=Object.create(null);if(n.r(o),Object.defineProperty(o,"default",{enumerable:!0,value:t}),2&e&&"string"!=typeof t)for(var c in t)n.d(o,c,function(e){return t[e]}.bind(null,c));return o},n.n=function(t){var e=t&&t.__esModule?function(){return t.default}:function(){return t};return n.d(e,"a",e),e},n.o=function(t,e){return Object.prototype.hasOwnProperty.call(t,e)},n.p="",n(n.s="./src/js/main.js")}({"./src/js/dropdownList.js":
/*!********************************!*\
  !*** ./src/js/dropdownList.js ***!
  \********************************/
/*! exports provided: default */function(module,__webpack_exports__,__webpack_require__){"use strict";eval("__webpack_require__.r(__webpack_exports__);\nvar dropdownList = function dropdownList() {\n  var contentListCompany = document.querySelector('.content__list-company');\n  var contentTitleCompany = document.querySelector('.content__title-company');\n  var contentListInfo = document.querySelector('.content__list-info');\n  var contentTitleInfo = document.querySelector('.content__title-info');\n  var contentListCatalog = document.querySelector('.content__list-catalog');\n  var contentTitleCatalog = document.querySelector('.content__title-catalog');\n  var contentListCabinet = document.querySelector('.content__list-cabinet');\n  var contentTitleCabinet = document.querySelector('.content__title-cabinet');\n  contentTitleCompany.addEventListener('click', function () {\n    contentListCompany.classList.toggle('content__list-active');\n    contentTitleCompany.classList.toggle('content__title-active');\n  });\n  contentTitleInfo.addEventListener('click', function () {\n    contentListInfo.classList.toggle('content__list-active');\n    contentTitleInfo.classList.toggle('content__title-active');\n  });\n  contentTitleCatalog.addEventListener('click', function () {\n    contentListCatalog.classList.toggle('content__list-active');\n    contentTitleCatalog.classList.toggle('content__title-active');\n  });\n  contentTitleCabinet.addEventListener('click', function () {\n    contentListCabinet.classList.toggle('content__list-active');\n    contentTitleCabinet.classList.toggle('content__title-active');\n  });\n};\n\n/* harmony default export */ __webpack_exports__[\"default\"] = (dropdownList);\n\n//# sourceURL=webpack:///./src/js/dropdownList.js?")},"./src/js/main.js":
/*!************************!*\
  !*** ./src/js/main.js ***!
  \************************/
/*! no exports provided */function(module,__webpack_exports__,__webpack_require__){"use strict";eval('__webpack_require__.r(__webpack_exports__);\n/* harmony import */ var _dropdownList__WEBPACK_IMPORTED_MODULE_0__ = __webpack_require__(/*! ./dropdownList */ "./src/js/dropdownList.js");\n\nwindow.addEventListener(\'DOMContentLoaded\', function () {\n  Object(_dropdownList__WEBPACK_IMPORTED_MODULE_0__["default"])();\n});\n\n//# sourceURL=webpack:///./src/js/main.js?')}});
//# sourceMappingURL=main.js.map
